version: '3.4'

services:
  interview.api:
    image: ${DOCKER_REGISTRY-}interviewapi
    build:
      context: .
      dockerfile: src/Interview.Api/Dockerfile
    depends_on:
      - "mssql-test-data"

  mssql-test-data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: interview-db
    ports:
      - "5050:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "YourStrong@Passw0rd"